apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth0-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth0-service
  template:
    metadata:
      labels:
        app: auth0-service
    spec:
      containers:
      - name: app-auth0
        image: nihasahmeda/app-auth0:v1 # public hosted repo
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: auth0-service
spec:
  selector:
    app: auth0-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30010
